// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuprTyJCF7ZpkNcnYfIY2ydPIxSgCvmqE',
    appId: '1:239299555987:web:416dc49706d751d0105366',
    messagingSenderId: '239299555987',
    projectId: 'cams-6b2af',
    authDomain: 'cams-6b2af.firebaseapp.com',
    storageBucket: 'cams-6b2af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5zypuMI9yA-RpM63qxzzKdBLtYtHny4w',
    appId: '1:239299555987:android:2a941bdc490a0c83105366',
    messagingSenderId: '239299555987',
    projectId: 'cams-6b2af',
    storageBucket: 'cams-6b2af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi1CFGx7hBwYO_6M3BnWGjD4xLWxXG-E8',
    appId: '1:239299555987:ios:7e7ac0aa8debcc6e105366',
    messagingSenderId: '239299555987',
    projectId: 'cams-6b2af',
    storageBucket: 'cams-6b2af.firebasestorage.app',
    androidClientId: '239299555987-a4237megd3o2jjob0olbelhb0414fa61.apps.googleusercontent.com',
    iosClientId: '239299555987-29t0aadv155dv180pvjtjjj8rglq8c94.apps.googleusercontent.com',
    iosBundleId: 'com.example.fprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi1CFGx7hBwYO_6M3BnWGjD4xLWxXG-E8',
    appId: '1:239299555987:ios:7e7ac0aa8debcc6e105366',
    messagingSenderId: '239299555987',
    projectId: 'cams-6b2af',
    storageBucket: 'cams-6b2af.firebasestorage.app',
    androidClientId: '239299555987-a4237megd3o2jjob0olbelhb0414fa61.apps.googleusercontent.com',
    iosClientId: '239299555987-29t0aadv155dv180pvjtjjj8rglq8c94.apps.googleusercontent.com',
    iosBundleId: 'com.example.fprojects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuprTyJCF7ZpkNcnYfIY2ydPIxSgCvmqE',
    appId: '1:239299555987:web:c77cd02d3aeb9c42105366',
    messagingSenderId: '239299555987',
    projectId: 'cams-6b2af',
    authDomain: 'cams-6b2af.firebaseapp.com',
    storageBucket: 'cams-6b2af.firebasestorage.app',
  );

}